language: node_js

node_js:
  - node
  - 8
  - 7
  - 6

cache: yarn

before_install: yarn global add greenkeeper-lockfile@1

before_script: greenkeeper-lockfile-update
script:
  - yarn run eslint
  - yarn run spellcheck
  - yarn run flow:check
  - yarn run flow:annotations
  - yarn run flow:coverage -t text
  - yarn run pretest:integration
  - ./node_modules/.bin/react-scripts test --env=jsdom --coverage
  - ./node_modules/.bin/react-scripts build
after_script: greenkeeper-lockfile-upload

before_deploy:
  - yarn run build:prod
  - yarn run build:cli
  - yarn run build:stats
  - yarn run build:storybook
deploy:
  - provider: pages
    target_branch: gh-pages
    local_dir: docs
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
      repo: pinterest/bonsai
      branch: master
      node: node
  - provider: npm
    api_key: $NPM_API_KEY
    email: "ryan@ryanalbrecht.ca"
    on:
      repo: pinterest/bonsai
      tags: true
      node: node
